<a href="https://colab.research.google.com/github/hyunlimy/SNUCM_medical_datascience/blob/main/SNUCM_medical_data_science_basic_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preliminaries I : Pandas DataFrame
- Author : **Hyun-Lim Yang, Ph.D.**<br>
Research Assistant Professor @
Seoul National University Hospital <br>
Department of Anesthesiology and Pain Medicine
- E-mail : hlyang{_at_}snu{_dot_}ac{_dot_}kr
***


## Import packages

In [ ]:
import pandas as pd
import numpy as np

## Pandas Data structure
### DataFrame
> - R의 dataframe  데이터 타입과 유사
> - Tabular data type 을 지원하여 정형 데이터를 분석하기 쉬움
> - Columns / Row (data) / Index 로 구성


In [ ]:
df_dic = pd.DataFrame({"A":[1,4,7], "B":[2,5,8], "C":[3,6,9]})
df_dic

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df_np = pd.DataFrame(np.array([[1,2,3], [4,5,6], [7,8,9]]))
df_np

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## DataFrame indexing
### Index by columns
> - 컬럼 이름으로 바로 인덱싱 가능

In [ ]:
df_dic['A']

0    1
1    4
2    7
Name: A, dtype: int64

In [ ]:
df_dic[['A', 'B']]

A  B
0  1  2
1  4  5
2  7  8

### index by condition
> - 조건을 통해 row(data) 를 indexing 가능

In [ ]:
row_index = np.array([True, False, True])
df_dic[row_index]

A  B  C
0  1  2  3
2  7  8  9

In [ ]:
df_dic[df_dic.index % 2 == 0]

A  B  C
0  1  2  3
2  7  8  9

## DataFrame attributes
### Get index of DataFrame
> - `.index` : DataFrame의 index를 반환함

In [ ]:
df_np.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
list(df_np.index)

[0, 1, 2]

### Get value of DataFrame
> - `.values` : DataFrame의 값을 array 형태로 반환함

In [ ]:
df_np.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
df_dic['A'].values

array([1, 4, 7])

In [ ]:
df_dic[['A', 'C']].values

array([[1, 3],
       [4, 6],
       [7, 9]])

## DataFrame functions
### notnull()
> - `na` 혹은 `NaN` 값 비교를 하여 boolean을 반환함 (없으면 `True`)

In [ ]:
df_na = pd.DataFrame({"A":[1,np.nan,7], 
                      "B":[2,5,np.nan], 
                      "C":[3,6,9]})
df_na

A    B  C
0  1.0  2.0  3
1  NaN  5.0  6
2  7.0  NaN  9

In [ ]:
df_na.notnull()

A      B     C
0   True   True  True
1  False   True  True
2   True  False  True

In [ ]:
df_na[df_na['A'].notnull() & df_na['B'].notnull()]

A    B  C
0  1.0  2.0  3

### fillna()
> - `na` 혹은 `NaN` 값 위치에 모두 특정 값을 대입함

In [ ]:
df_fna = pd.DataFrame({"A":[1,np.nan,7], 
                      "B":[2,5,np.nan], 
                      "C":[3,6,9]})
df_fna

A    B  C
0  1.0  2.0  3
1  NaN  5.0  6
2  7.0  NaN  9

In [ ]:
df_fna.fillna(0)

A    B  C
0  1.0  2.0  3
1  0.0  5.0  6
2  7.0  0.0  9

In [ ]:
df_fna.fillna('not available')

A              B  C
0              1              2  3
1  not available              5  6
2              7  not available  9